ratings:
    paths:
        - "**.py"
exclude_paths:
    - "CslBot.egg-info/**"
    - "cslbot/static/**"
    - "cslbot/templates/**"
    - "**.rst"
    - "**.sh"
engines:
    fixme:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - python
    radon:
        enabled: true
    pep8:
        enabled: true
