ratings:
    paths:
        - "**.py"
engines:
    fixme:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - python
    radon:
        enabled: true
    pep8:
        enabled: true
