language: python

addons:
    postgresql: "9.4"

python:
    - 3.4

cache:
    directories:
        - $HOME/.cache/pip

install:
    - pip install flake8
    - pip install -r requirements.txt

before_script:
    - psql -U postgres -c 'create database ircbot'
    - sed "s#engine:#\0 postgresql://postgres@/ircbot#" config.example > config.cfg

script:
    - flake8 --max-line-length=1000 .
    - ./scripts/test.py
