language: python

addons:
    postgresql: "9.4"

python:
    - 3.4
env:
    global:
        secure: lj+VOYMzDqhCTVpnGtkBEBRRCi5nQHgK6SR88tZLI34sn1eQQGyc8hM/BStIBF9iaC0+5b3GaRrEtfRQ3jwxUrcm1fPMOhFlkqb/WH3Yaidp0goEzlvE8UDdfZSO3UpjfgnYTpqBCKskGcfb9iz1CRI02+PtgzSfGuZ8sntgOLM= 

install:
    - pip install flake8 sphinx
    - pip install -r requirements.txt

before_script:
    - psql -U postgres -c 'create database ircbot'
    - sed "s#engine:#\0 postgresql://postgres@/ircbot#" config.example > config.cfg
    - git clone git://github.com/tjcsl/cslbot-tjhsst.git commands/tjhsst

script:
    - flake8 --max-line-length=1000 .
    - ./scripts/test.py
    - ./scripts/gendocs.sh

after_success:
    ./scripts/deploy_docs.sh
